// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("ignitebeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJy0WNty2zgSfddXdOVpt0pibeyNa0sPW+OxXRPVxIlr4jwrLaBFYkwCDABa1nz9FC68idTFscZPxu2cA6D7NMTJDJ5oO4cVoZ0AWGFzmsOvocXJMC1KK5Scw/8nAAA3SloU0gBTRaGkXwdrQTk3gM8oclzlBEIC5jnQM0kLdluSSSYQp80nHmgGEgsKxIn71/eOcrq/x4z8AlBrsBl5hWBIciFT35GrFAoyBlMyCSw6s/wyYRooQ9YJdONMybVIK42ODtYip6nrd4No4Rnzyq2EyhD3mMK6plS2C+aXQKaMjUxx/qPyVD0dUzfmu7675vcGR/kd79eVDA+tZjx+cI02NKDJVloSh9XWU6mSHI1MwWyNpQKUhE0mWNYK75ydrqQUMh1RY0VBfyl5gpp65j+p5pm0EUoeFxMn1mHlw9lffkrSSSEONhMmhHLSD913v7itGItF+S6CulifA0dbn4OmH5XQxOdgdVV3rpUu0Pbm0QsWpUu96yqtjIWLK5vBxX/eX03h/cX88sP8w2VyeXlx2ul6SbAJgUwxDV2CaGJKc9igafe3symLqTnMcq1XwmrUWz83nBZDZwU+3kvS4aJQct+wGqVBZtv7COe0QxzcoXeOavUnsTrXQmMZRp5ou1GaHxbaeFVlSLc55QwqkO0oIK2V7glItarKwyR3blHtgCwwuvhFzoWbizkIuVYusxka71+exyR1MERXrAFrNdHMmv5ak6UX2+ncI6uVFnGSAQFTfIieK5m+Bt2BDKEd1gC6f2cnoYcwiSWK5aribY26cU0otXoWnNw2LXK0OF627uMorLUqAlKz1Li7ai0IOV/6Ccsa0s1kZIzSe6uYm5r4VUkNu5vYxI5k7+dOeesrTOBBGSNc4PqaZAA1OcAppIymoDRwkQqLuWKEMtmrTUhjUTJaiiOps4gTYXFbS3JFBApkmZC7qTvGcLwyNRzdun4aS5yw7MRZc872IimIi6o4zH4fIHyIvY48PnNELux22Sl5jYLKzAiNnb1nR4y0AwS+Ioq22gkT5AjTlrkDIee9sbnVRkocmb2cHnpxidPym1JpTiHT9rNrSo+W2j/8nGP7i4nOFXvy+RMz/bZuj4CHMTAWrbPfPCfmarZP8zDmctZkSttlqABzWGNu3KWhZJnSNd+syfJJ35TrLTeyYLQ+7PPxWBNIJ4K/zRO/SfGjohYQBB9z9YauGCsfr2LsxoWHq1+nUYB7SKwqkVtQ8pCUjhn8pJKbhtNhHeLKcUW5GbD13hJw+D1xRMvCn0TgaYLWBXMbsh9DawRk4R4DnUB1VW5gPW1suv6jkRm5XxeXb7+Tj/FnxfA2zhTpwSBGghw1y4QlZit9hj304OBflKQJvPzvann13ymgLqZQlmwKhSjNv4dSlEnKHK170r9NyZevUANFDYykVWYK1aqStprCRkiuNntE9H/x/LyGiDPKscZC5Ns3UwSYuElNPEM7BU4rgXIKa020MvzQbkU5kNDrOsD+SRjrDG3xMEPONRlDZkhQIHvbJmuaDDXfoKaWbAqVqTDPt3B/fdPVUPvIU7UiLcmSad3k927fCG073jyD+2/aFhS6XnK4LLaLjhpQTzS8yoZKxc9QHjonUCoevG2UqnqrNe0wObxRazUlsvNtqkUckrlfYGc9QYe45whPLa6nEQU0KLAcMqGUyvrvX2ej60COc57zwdLhZb23yyHaMzzZRnkDbnQYkUphqf/Bt9fXRd+T8ExV0u48hjufDka/eu0R/fDp7vrrHXx7uL1+vIPbLzff7u8+P14/Lr58nvwdAAD//7KmnOQ="
}
